### ISSUE TITLE
Configure webpack-dev-server and use HTML5 paths

### ISSUE THREAD

**Issue by cmelion** [cmelion/generator-ng2-webpack#10]
In order to use HTML5 mode routing and support refresh on non-index routes, you have to configure your server to redirect every “missing” route to the root URL.  Since this is the preferred mode in production, we should mirror that in the development environment.

**Comment by pavanpodila** [comment]
There is a flag for that in `devServer`, called `historyApiFallback`

**Comment by cmelion** [comment]
Yes, I remember now.  I'm using that on my react-webpack projects.

**Comment by cmelion** [comment]
Closing with #17
