### ISSUE TITLE
Start browser once build is ready

### ISSUE THREAD

**Issue by kuncevich** [cmelion/generator-ng2-webpack#13]
After `npm start` webpack successful build it is nice when browser opening the url.

I used this trick with node `start http://localhost:8080 && node myserver.js` however in case of webpak it is just partly working. If I have such script `start http://localhost:8080 && npm run server` the browser opening the page before webpack is ready so manual page refresh required after webpack is finished build.

**Comment by cmelion** [comment]
@kuncevich, great suggestion! I like that approach as well.

**Comment by pavanpodila** [comment]
There is also an open flag for devserver

Thanks,
Pavan

**Comment by cmelion** [comment]
@pavan  I tried --open and it didn't work with the current configuration.  No errors so not sure why.
I spun up a quick server.js that worked great except that it couldn't find the public image (the shield) with the following:

```

new WebpackDevServer(webpack(config), {
    publicPath: config.output.publicPath,
    hot: true,
    historyApiFallback: true,
    proxy: proxy,
    quiet: false,
    noInfo: false,
    watchOptions: {
        aggregateTimeout: 300,
        poll: true
    },
    headers: headers,
    stats: {
        chunks: false,
        colors: true
    }
}).listen(3000, 'localhost', function (err, result) {
        if (err) {
            console.log(err);
        } else {
            open(config.host);
        }

        console.log('Listening at localhost:3000');
    });
```

**Comment by cmelion** [comment]
I tried adding a post server task and it didn't work but this does:
  `  "preserver": "open http://localhost:8080"`

**Comment by kuncevich** [comment]
I am on Win 10 so `"preserver": "start http://localhost:8080"` working great.

**Comment by cmelion** [comment]
Leaving this up to the developer to modify package.json as desired.  To many environment issues to deal with:  Windows, Mac, Linux and Docker containers.
