### ISSUE TITLE
How to update current project with a new generator version?

### ISSUE THREAD

**Issue by kuncevich** [cmelion/generator-ng2-webpack#16]
Lets say I create a project with `generator-ng2-webpack` but then some time later generator gets updated. What is the best way to update the current project with the latest `generator-ng2-webpack`?

**Comment by cmelion** [comment]
After performing an `npm update generator-ng2-webpack`,  make sure you have committed everything or have a backup, then just scaffold out over the project again. yo will ask you for each file if you want to overwrite. For those files you haven't edited, just say yes. For the other ones, type d for diff and see what's changed.  You may need to perform `npm install `or `npm rebuild`.  Sub-generators will work in a similar fashion but need to be run one at a time on existing components, services, etc.

**Comment by kuncevich** [comment]
OK I see. Thanks.

**Comment by cmelion** [comment]
I'm running Webstorm so my preferred method of updating generated projects is to select 'a' for all and just overwrite everything without further prompts and view local-history on the top-level folder.  I find it easier to select  just the files I care about, from the changed files list, one at a time and do a visual diff.
