### ISSUE TITLE
Build should enable prod mode

### ISSUE THREAD

**Issue by cmelion** [cmelion/generator-ng2-webpack#19]
`Angular 2 is running in the development mode. Call enableProdMode() to enable the production mode.`

**Comment by henry-martinez** [comment]
I'm not sure if this is the appropriate solution, but I changed the 'prod' to 'build' in the bootstrap.ts to enableProdMode() 

this..
`
// depending on the env mode, enable prod mode or add debugging modules
if (process.env.ENV === 'prod') {
    enableProdMode();
} else {
    ENV_PROVIDERS.push(ELEMENT_PROBE_PROVIDERS);
}
`

to this
`
// depending on the env mode, enable prod mode or add debugging modules
if (process.env.ENV === 'build') {
    enableProdMode();
} else {
    ENV_PROVIDERS.push(ELEMENT_PROBE_PROVIDERS);
}

`

**Comment by cmelion** [comment]
Yes, simply picking up the environment from the npm task makes perfect sense.

Thanks  @henry-martinez!
