### ISSUE TITLE
Bower Components

### ISSUE THREAD

**Issue by iosonosempreio** [cmelion/generator-ng2-webpack#21]
Hello! I'm new with Webpack and Angular2 (so please forgive me if the following is a stupid question) and I need to use this JS library: [FileSaver.js](https://github.com/eligrey/FileSaver.js/).

I know It is a Bower component and I have to edit the `webpack.config.js`in order to make this kind of modules working in the environment of Webpack. I found this guide: [link](https://webpack.github.io/docs/usage-with-bower.html), but unfortunately the configuration structure seems to be different from the one I found in the guide (we have `function makeWebpackConfig()`insted of the plain configuration).

I inserted `bower_components` here (is it fine to do that?) and I added the importer and the plugin as well:
```
config.resolve = {
        cache: !isTestEnv,
        root: root("bower_components"),
        // only discover files that have those extensions
        extensions: prepend(['.ts','.js','.json','.css', '.scss', '.html'], '.async'), // ensure .async.ts etc also works
        alias: {
            'app': 'src/app',
            'common': 'src/common'
}
```

Then, in the `vendor.ts` I've done `import 'file-saver.js'`, but for some reason is not working.

Any Idea?

Thanks!

**Comment by cmelion** [comment]
Did you try https://www.npmjs.com/package/filesaver.js ?

From the teminal in your project root:
`npm install --save-dev filesaver.js`

Add this to the component you want to use filesaver with:
`import filesaver from 'filesave.js'`

**Comment by iosonosempreio** [comment]
Thanks for the reply.
It is not working, should I write any loader for that?

**Comment by iosonosempreio** [comment]
I found a solution that is working for now, even if I believe it not the correct way of doing this thing.
```
var d3 = require('d3');
var saveAs = require('filesaver.js');
console.log("saveAs",saveAs.saveAs);
saveAs = saveAs.saveAs;
```

Please, does anybody have a better example to show me?

**Comment by cmelion** [comment]
I actually use the same approach, especially in TSX files.
