### ISSUE TITLE
Consider making linting optional

### ISSUE THREAD

**Issue by mattxo** [cmelion/generator-ng2-webpack#26]
```[177, 13]: misplaced opening brace
[187, 5]: misplaced opening brace
[197, 5]: misplaced opening brace
```

Fills up the browser console when developing if you use new line bracing, which tends hides to hide exceptions etc.

**Comment by cmelion** [comment]
@mattxo out of curiosity, can you provide a sample of the code that is generating the messages?

IMHO opinion, linting is never optional.  I prefer to relax on a case-by-case basis with inline comments.

You are also free to modify the lint config or turn of linting altogether in webpack-config:108.
Just remove the preloader.

preLoaders: isTestEnv ? [] : [{test: /\.ts$/, loader: 'tslint'}],

**Comment by mattxo** [comment]
Oh, its in there! *forehead slap* Forget I spoke!

Sure, I come from a C# background so I tend to format code like


```
export class MyAwesomeClass
{
    constructor() 
    {
    }
}
```
