### ISSUE TITLE
Typings installation can fail during npm install when terminal is full-screen

### ISSUE THREAD

**Issue by cmelion** [cmelion/generator-ng2-webpack#31]
Solution:  Exit full-screen and re-run npm install.

SyntaxError: Invalid regular expression: /.{1,0}/: numbers out of order in {} quantifier.
    at new RegExp (native)
    at breakLines (/home/yeoman/client/node_modules/typings/node_modules/insight/node_modules/inquirer/lib/utils/screen-manager.js:108:15)
.
.
.
(/home/yeoman/client/node_modules/typings/node_modules/insight/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:63:31)

**Comment by katrinsharp** [comment]
Amazing! Thanks!
