### ISSUE TITLE
Allow 100% code coverage

### ISSUE THREAD

**Issue by mattxo** [cmelion/generator-ng2-webpack#35]
To allow 100% code coverage (not currently possible because of the typescript helper functions __extends, __decorate etc), one can 

1. `npm install ts-helpers --save-dev`
2. add `import 'ts-helpers'` to the top of app/root.spec.ts and bootstrap.ts
3. add `'noEmitHelpers : true'` to tsconfig.json

**Comment by cmelion** [comment]
Thanks @mattxo can you issue a PR?

**Comment by mattxo** [comment]
Sure :)

**Comment by cmelion** [comment]
Thanks @mattxo!
