### ISSUE TITLE
Weird hidden characters after build

### ISSUE THREAD

**Issue by mushdigital20** [cmelion/generator-ng2-webpack#40]
I'm using the build on SalesForce Cloud market as a static resource, I wasn't and error from the application when trying to save the result js files, I've isolated the problem by removing the line by line and I've found weird characters that are not allowed in a Html context. one of the examples of what I'm talking about is this '[' if you try to delete the first quote the cursor doesn't move the first time as there is a hidden char between the visible ones, another problem I've found was Ft=["","​","￾"].

Let me know if you need more info

**Comment by cmelion** [comment]
@mushdigital20 can you share a version of the generated app that exhibits the problem?

**Comment by cmelion** [comment]
closing
