### ISSUE TITLE
Production install impossible

### ISSUE THREAD

**Issue by gruber76** [cmelion/generator-ng2-webpack#50]
On a fresh download, running "npm install --production" fails because the postinstall routine (that is unnecessary for production) calls on two dev dependencies.

**Comment by cmelion** [comment]
This issue was caused by changes to the entry-point in webpack-config, you can fix it by reverting to the version below, will push out a fix ASAP:
```
    /**
     * Entry
     * Reference: http://webpack.github.io/docs/configuration.html#entry
     */
    config.entry = isTestEnv ? {} : {
        'vendor': './src/vendor.ts',
        'app': './src/bootstrap.ts' // our angular app
    };
```
