### ISSUE TITLE
Importing lodash

### ISSUE THREAD

**Issue by Gelio** [cmelion/generator-ng2-webpack#61]
I have installed typings for lodash and included `import 'lodash';` in *vendors.ts*, the app works, but in Visual Studio Code I get an error saying, that `_` cannot be found.

I've tried importing lodash at the beginning of the file that needs it, but to no avail. `import 'lodash';` at the top does nothing, whereas `import * as _ from 'lodash';` leads to no error in VSCode, but an unresolved module in Angular2.

How to get rid of that error message and properly import lodash?

**Comment by cmelion** [comment]
For the entire library ==> `import _ from 'lodash';`
For a specific utility function ==> `import find from 'lodash/find';`

**Comment by Gelio** [comment]
I don't know if it's an issue connected with Visual Studio Code, but it does not work for me, unfortunately.

``` javascript
import _ from 'lodash';
```

leads to
![](https://i.gyazo.com/524327fa38e6771d5b977688ff33e83a.png)

``` javascript
import find from 'lodash/find';
```
leads to
![](https://i.gyazo.com/aef5392d8da20d5140485320c9294f3a.png)

This is how my typings.json file looks like:

``` json
{
    "ambientDevDependencies": {
        "jasmine": "github:DefinitelyTyped/DefinitelyTyped/jasmine/jasmine.d.ts#dd638012d63e069f2c99d06ef4dcc9616a943ee4"
    },
    "ambientDependencies": {
        "es6-shim": "github:DefinitelyTyped/DefinitelyTyped/es6-shim/es6-shim.d.ts#6697d6f7dadbf5773cb40ecda35a76027e0783b2",
        "node": "github:DefinitelyTyped/DefinitelyTyped/node/node.d.ts#aee0039a2d6686ec78352125010ebb38a7a7d743"
    },
    "dependencies": {
        "lodash": "registry:npm/lodash#4.0.0+20160416211519"
    }
}
```

Here's the lodash typings file that I installed: [https://raw.githubusercontent.com/typed-typings/npm-lodash/7ccf9dc406a792d702067f4eab0fa8df4109fcaa/index.d.ts](https://raw.githubusercontent.com/typed-typings/npm-lodash/7ccf9dc406a792d702067f4eab0fa8df4109fcaa/index.d.ts)

**Comment by Gelio** [comment]
I think I may have solved it now. The solution to importing the whole lodash library is:
``` javascript
import * as _ from 'lodash';
```

And to import a specific function:
``` javascript
import {find} from 'lodash';
```

Same goes for RxJS, for instance
``` javascript
import * as Rx from 'rxjs';
````

I'm leaving it out here for other people to see. I would recommend putting this information in the README. I can make a pull request if you'd like.

**Comment by cmelion** [comment]
@Gelio, thanks for following up.  I'll add a link in the README to a Visual Studio wiki entry.  The wiki is open to the public so you can elaborate on Visual Studio specific issues there.

FWIW, when you perform:
` import {find} from 'lodash';`
you import the entire library and use ES6 destructuring to assign 'find' to a local variable of the same name.

`import find from 'lodash/find';` imports only find.

The syntax choice has different implications for the amount of code included in a given module but I must confess, I'm more familiar with ES6 than I am with Typescript and have no experience with Visual Studio's auto-completion.

**Comment by cmelion** [comment]
using [the wiki](https://github.com/cmelion/generator-ng2-webpack/wiki/Importing-vendor-libs) to capture issues like this one.

**Comment by mkozhukharenko** [comment]
same issue. Does anybody found a solution?
