### ISSUE TITLE
http issue 

### ISSUE THREAD

**Issue by itranga** [cmelion/generator-ng2-webpack#62]
I am getting an error when I am using below code to access rest API,

ORIGINAL EXCEPTION: TypeError: platform_browser_1.__platform_browser_private__.getDOM(...).getCookie is not a function

import {Component, OnInit, Injectable} from '@angular/core'; 
import {FORM_DIRECTIVES} from '@angular/common';
import {Http, Headers} from '@angular/http';

import {Api} from '../../services/api';

@Component({
    selector: 'home',
    directives: [...FORM_DIRECTIVES],
    providers: [Api],
    pipes: [],
    styles: [require('./style.scss')],
    template: require('./template.html')
})
@Injectable()
export class Home implements OnInit {

    constructor(http: Http) {
        this.http = http;
    }

    createAuthorizationHeader(headers: Headers) {
        headers.append('Authorization', 'Basic ' +
            btoa('username:password'));
    }

    getRandom() {
        let headers = new Headers();
        this.createAuthorizationHeader(headers);
        return this.http.get('http://localhost:3000/items', {
            headers: headers
        });
    }

    post(url, data) {
        let headers = new Headers();
        this.createAuthorizationHeader(headers);
        return this.http.post('http://localhost:3000/items', data, {
            headers: headers
        });
    }

    ngOnInit() {
        console.log('Hello Home');
    }
}

but when I use below code it works perfectly.

fetch('http://localhost:3000/items').then((response) => {
            return response.json();
        }).then((data) => {

            console.log(data);

        }).catch((ex) => {
            console.error('Error fetching users', ex);
        });

but I want to use 1st function since I have to pass header values.

How can I solve it.

Thanks

**Comment by cmelion** [comment]
The example at https://github.com/cmelion/ng2-webpack-demo-app/blob/master/src/app/services/api/items/index.ts passes a header value on post and is part of a working example covering CRUD operations.  If you are willing to refactor your code into an redux/rx style I can likely be of assistance.

**Comment by itranga** [comment]
I try to install your demp app [ https://github.com/cmelion/ng2-webpack-demo-app ] . Got the same issue 
![getcookie-notfunction](https://cloud.githubusercontent.com/assets/399798/16608604/f480219c-436a-11e6-89ca-e72f5be27934.jpg)

**Comment by itranga** [comment]
I found the solution  . Please change  "@angular/http": "^2.0.0-rc.1",  to  "@angular/http": "2.0.0-rc.1", in package.json

**Comment by cmelion** [comment]
I see.  The generator is currently using rc.3 and your package.json is still referencing rc.1.
I have removed the caret(^) and the dependency now reads as  "@angular/http": "2.0.0-rc.3".
