### ISSUE TITLE
npm 'open' not recognized when using npm start - under windows 10

### ISSUE THREAD

**Issue by aliabuthahir** [cmelion/generator-ng2-webpack#74]
npm 'open' not recognized when using npm start - under windows 10

**Comment by cmelion** [comment]
The quick fix is to edit the start task in package.json:
```"start": "concurrently \"npm run server\" \"npm run docker-client\"",```

You will then need to manually open http://localhost:2368 (assuming the default configuration)

If you would like to try Docker Beta for Windows (recommended) you can use the following approach:

## Docker Quick Start
Steps:

* Open a terminal
* run `docker-compose up`
* Once processing completes, open http://localhost:2368

notes: 

* to get the latest image run `docker-compose pull`
* on Windows inotify is not working so fall back to [polling](http://andrewhfarmer.com/webpack-watch-in-vagrant-docker/)
* for easy access to volumes or terminal and browser instances consider using Kitematic

**Comment by aliabuthahir** [comment]
yep!

manually we are able to open the app in web browser.  may be we need a fix in the script for the generator, since it feels like a dependency failure.

**Comment by aliabuthahir** [comment]
Hi,

I've attached the npm debug log for your perusal. Also as we know it probably is not a npm issue.

[npm-debug.zip](https://github.com/cmelion/generator-ng2-webpack/files/529673/npm-debug.zip)

Regards,
Ali

**Comment by cmelion** [comment]
```
23 error Failed at the app@0.0.0 delayed-open script 'sleep 5 && opn http://localhost:2368'.
```
That's strange, in the log, it's "opn" instead of "open"

**Comment by aliabuthahir** [comment]
yep!

modified the package.json to make use of 'opn' npm package instead of 'open' for the later was failing.

Regards,
 Ali

**Comment by cmelion** [comment]
Ahh, thanks.  F.Y.I. I do accept Pull Requests.

**Comment by cmelion** [comment]
@aliabuthahir The delayed open is really just there to prevent the browser from displaying not-found messages.  Sleep prevents that on Mac OSX, but does not work in Windows.  Looking into alternatives.

**Comment by cmelion** [comment]
ok this works for me on Windows 10 and Mac OSX:
``` npm install --save-dev system-sleep ```

use "opener" instead of open
```"delayed-open": "sleep 5 && opener http://localhost:2368",```

**Comment by cmelion** [comment]
@allabuthahir Closing this issue.  Feel free to re-open if you run into any problems.
